/**
 * Build-time sitemap generator.
 * Run: node scripts/generate-sitemap.mjs
 * Integrated into the build via package.json: "build": "node scripts/generate-sitemap.mjs && vite build"
 *
 * Outputs public/sitemap.xml containing every static page + all 480 asset pages.
 * Static URLs: ~10 | Asset URLs: 480 | Total: ~490
 */

import { writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { join, dirname } from 'node:path'

const __dir = dirname(fileURLToPath(import.meta.url))

// assets.js uses only ES module exports and plain JS — safe to import with Node
const { ASSETS } = await import(join(__dir, '../src/data/assets.js'))

const BASE_URL = 'https://videsaur.co.in'
const TODAY = new Date().toISOString().split('T')[0]

function toSlug(str) {
  return str
    .toLowerCase()
    .replace(/[^a-z0-9\s-]/g, '')
    .replace(/\s+/g, '-')
    .replace(/-+/g, '-')
    .replace(/^-|-$/, '')
}

function toMemeSlug(asset) {
  return `${toSlug(asset.title)}-${asset.id}`
}

const STATIC_PAGES = [
  { path: '/',               priority: '1.0', changefreq: 'daily'   },
  { path: '/trending',       priority: '0.9', changefreq: 'daily'   },
  { path: '/videos',         priority: '0.8', changefreq: 'daily'   },
  { path: '/gifs',           priority: '0.8', changefreq: 'daily'   },
  { path: '/templates',      priority: '0.8', changefreq: 'weekly'  },
  { path: '/sounds',         priority: '0.7', changefreq: 'weekly'  },
  { path: '/guide',          priority: '0.6', changefreq: 'monthly' },
  { path: '/about',          priority: '0.5', changefreq: 'monthly' },
  { path: '/privacy',        priority: '0.4', changefreq: 'monthly' },
  { path: '/terms',          priority: '0.4', changefreq: 'monthly' },
  { path: '/content-policy', priority: '0.4', changefreq: 'monthly' },
]

const memePages = ASSETS.map((asset) => ({
  path: `/meme/${toMemeSlug(asset)}`,
  priority: '0.7',
  changefreq: 'monthly',
}))

const allPages = [...STATIC_PAGES, ...memePages]

const urlset = allPages
  .map(
    (p) => `  <url>
    <loc>${BASE_URL}${p.path}</loc>
    <lastmod>${TODAY}</lastmod>
    <changefreq>${p.changefreq}</changefreq>
    <priority>${p.priority}</priority>
  </url>`,
  )
  .join('\n')

const xml = `<?xml version="1.0" encoding="UTF-8"?>
<!--
  Auto-generated by scripts/generate-sitemap.mjs at build time.
  Do not edit manually — re-run "node scripts/generate-sitemap.mjs" or "npm run build".
  ${allPages.length} total URLs: ${STATIC_PAGES.length} static + ${memePages.length} meme pages
-->
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${urlset}
</urlset>
`

const outPath = join(__dir, '../public/sitemap.xml')
writeFileSync(outPath, xml, 'utf8')
console.log(
  `✓ sitemap.xml → ${allPages.length} URLs (${memePages.length} meme pages + ${STATIC_PAGES.length} static)`,
)
